server:
  port: 8001
spring:
  profiles:
    active: local
    group:
      local: logging-level-local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/chat_center
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  data:

    redis:
      host: localhost
      port: 6379

    mongodb:
      host: localhost
      port: 27017
      database: test

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-center

cloud:
  aws:
    credentials:
      accessKey: ${aws-access-key}
      secretKey: ${aws-secret-key}
    s3:
      bucket: ${aws-s3-buket}
    region:
      static: ap-northeast-2
    stack:
      auto: false
